[tui]
status_line = ["model-with-reasoning", "current-dir", "context-remaining", "context-used", "fast-mode"]
[tui.keymap.editor]
insert_newline = "ctrl-q"

[tui.model_availability_nux]
"gpt-5.5" = 4

[projects."/home/dbalatero/.config/nixpkgs"]
trust_level = "trusted"

[projects."/home/dbalatero/code/neovim"]
trust_level = "trusted"

[projects."/Users/dbalatero/.config/nixpkgs"]
trust_level = "trusted"

[projects."/Users/dbalatero/code/ynab"]
trust_level = "trusted"
