# HOSTNAME - Brief description of this machine
{
  config,
  lib,
  pkgs,
  ...
}: {
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Common NixOS configuration (SSH, users, base packages, etc.)
    ../common/nixos

    # Optional: Uncomment for desktop environment (KDE, gaming, audio, etc.)
    # ../common/desktop
  ];

  # Hostname (CHANGE THIS!)
  networking.hostName = "HOSTNAME";

  # Boot loader configuration
  # Adjust based on your boot setup (UEFI vs BIOS)
  boot.loader = {
    efi.canTouchEfiVariables = true;

    grub = {
      enable = true;
      device = "nodev";  # For UEFI systems
      efiSupport = true;
      # useOSProber = true;  # Uncomment to detect other OSes (Windows, etc.)
    };
  };

  # Timezone (optional override - defaults to America/New_York)
  # time.timeZone = "America/Los_Angeles";

  # Add any host-specific packages here
  # environment.systemPackages = with pkgs; [
  #   # your packages
  # ];

  # Add any host-specific configuration here
}
