# __NIXOS_HOSTNAME__
# __NIXOS_DESCRIPTION__
{...}: {
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Common NixOS configuration (SSH, users, base packages, etc.)
    ../common/nixos

    # Optional: Uncomment for desktop environment (KDE, gaming, audio, etc.)
    # ../common/desktop
  ];

  # Hostname
  networking.hostName = "__NIXOS_HOSTNAME__";

  # Boot loader configuration
  boot.loader.grub = {
    enable = true;
    device = "/dev/sda";
  };

  # Automatically grow root partition to fill available disk space (useful for VMs)
  boot.growPartition = true;

  # Static IP configuration
  networking.interfaces.eth0.ipv4.addresses = [
    {
      address = "__NIXOS_STATIC_IP__";
      prefixLength = 24;
    }
  ];

  networking.defaultGateway = {
    address = "192.168.1.1";
    interface = "eth0";
  };

  networking.nameservers = ["192.168.1.169"];

  # Add any host-specific packages here
  # environment.systemPackages = with pkgs; [
  #   # your packages
  # ];

  # Add any host-specific configuration here
}
